const Blurb_1 = "Through shadowing, students get to see a glimpse into the everyday lives of physicians at Ronald Reagan and can visualize what kind of healthcare setting they imagine themselves working in. Our members form connections with medical personnel and, often times, receive mentorship from med students or residents who were in their positions before."

const departments = [
    {
        department: "Internal Medicine",
        description:
            "The Internal Medicine (IM) service is led by the IM rounding team, which consists of the attending physician, IM residents, and 1 rotating medical student. The IM rounding team conducts daily rounds where they visit the patients on their service. During rounds, the medical team presents the state of the patient, shares updates that happened overnight, discusses plans for treatment, and addresses the family’s/patient’s questions and concerns. Additionally, the IM team occasionally sees patients in the Emergency Room who need to be admitted into the hospital for further management. The IM department fosters an incredibly collaborative and thought-provoking space where PULSE members can ask questions and synthesize as much as they can from the physician-patient interaction that they observe.",
    },
    {
        department: "Pediatric Cardiology and Nephrology",
        description: "The Pediatrics Cardiology and Nephrology service is led by the Pediatrics GOLD rounding team, which consists of the attending physician and Pediatric residents. The Pediatrics GOLD rounding team conducts daily family-centered rounds on patients admitted for cardiology or nephrology-related pathologies. During rounds, the medical team presents the state of the patient, shares updates that happened overnight, discusses plans for treatment, and addresses the family’s/patient’s questions and concerns. Despite the complex cases this team manages on a daily basis, the Pediatrics Cardiology and Nephrology department fosters an incredibly collaborative and brave space where PULSE members can ask questions and synthesize as much as they can from the physician-patient interaction that they observe.",
    },
    {
        department: "General Pediatrics",
        description: "The General Pediatrics service is led by the Pediatrics SILVER rounding team, which consists of the attending physician, Pediatric residents, and rotating medical students. The SILVER team sees a wide spectrum of childhood morbidities. The Pediatrics rounding team conducts daily family-centered rounds where they visit the patients and families on their service. During rounds, the medical team presents the state of the patient, shares updates that happened overnight, discusses plans for treatment, and addresses the family’s/patient’s questions and concerns. Despite the strenuous number of patients this team sees on a daily basis, the Pediatrics department fosters an incredibly collaborative and brave space where PULSE members can ask questions and synthesize as much as they can from the physician-patient interaction that they observe.",
    },
    {
        department: "Neurology Stroke",
        description: "The Neurology Stroke service is led by the Stroke rounding team, which consists of the attending physician, Neurology Stroke residents, and rotating medical students. The Stroke rounding team conducts daily rounds where they visit the patients on their service. During rounds, the medical team presents the state of the patient, shares updates that happened overnight, discusses plans for treatment, and addresses the family’s/patient’s questions and concerns. Additionally, the Stroke team occasionally sees patients in the Emergency Room who present as an active Code Stroke or who need to be admitted into the Neurology wards for further management. While shadowing the team, PULSE members have also observed radiation scans, administration of TPA, and other life-threatening co-morbidities that manifest as a result of a stroke. The Neurology Stroke team fosters an incredibly collaborative and thought-provoking space where PULSE members can ask questions and synthesize as much as they can from the physician-patient interaction that they observe.",
    },
    {
        department: "General Neurology",
        description: "The General Neurology Department specializes in treating nervous system related injuries and disorders. As there is an emphasis on teamwork and education, the rounding team consists of an attending physician, neurology residents, and rotating medical school students. PULSE members have the unique opportunity to observe the clinical course of patients from admittance to discharge. As Neurology encompasses a broad array of neurological disorders, members are exposed to a wide variety of detection and diagnosis methods, such as imaging and physical examinations. Furthermore, members can observe the decision-making process and application of numerous treatment and management plans. Ultimately, members can gain insight into the team-oriented and highly engaging dynamic of the General Neurology Department.",
    },
    {
        department: "Cardiac Critical Care Unit",
        description: "The Cardiology Critical Care Unit (CCU) service is led by the CCU rounding team, which consists of an attending physician, Internal Medicine residents, and rotating medical students. Cardiology is such a vast field within medicine, where individuals seeking to become cardiologists must specialize in specific cardiology fellowships, one of them being the CCU. Within the CCU, our PULSE members have had the chance to observe patients get admitted into the CCU, discharged from the CCU, and visit the cardiac catheterization lab where different procedures are conducted. Additionally, the CCU team also sees patients in the emergency room who may need to be admitted to the CCU upon presentation of cardiac symptoms. In extreme cardiac emergencies, our PULSE members accompany the medical team onto the helipad to retrieve patients flown into Ronald Reagan Medical Center. The CCU is an intensely-paced environment that offers many unique learning opportunities for our members. ",
    },
    {
        department: "Cardiology Outpatient",
        description: "The Cardiology Outpatient service is led by an attending cardiologist who is sometimes joined by internal medicine residents, and or rotating medical students. Through the Cardiology Outpatient service PULSE students get to watch attendings take patient history, provide a full work up, and create a treatment plan. Attendings encourage learning by letting PULSE students listen to rare heart murmurs and explaining complex imaging, labs, or EKGs of patients. The Cardiology Outpatient service is busy with back to back patients exposure and intensive, hands-on learning experiences.",
    },
    {
        department: "Cardio Consults",
        description: "The Cardio Consults Department specializes in treating cases of cardiovascular disorders that are present in conjunction with disorders in other parts of the body. The cases that this department work with are complex cases that come from all over the hospital, so this team spends a majority of its time problem-solving and workshopping potential solutions. The rounding team consists of medical students, residents, a nurse practitioner, and a supervising attending. These cases are a unique opportunity for PULSE members to view the interdisciplinary nature of medicine. Even though this medical team is cardiology focused, they pull from a vast overall knowledge of the human body in order to understand how any decision will affect not just the heart but the patient’s health overall. Members are able to learn from physicians’ decision making, thought process, and ability to adapt to frequently changing circumstances. Ultimately, members can gain insight into a very challenging but fulfilling aspect of medicine.",
    },
    {
        department: "Emergency Medicine",
        description: "The Emergency Medicine Department understandably has no rounding team and is by far the most flux in nature of all the services that members shadow. Instead of the common scheduled visit, the calls that ED physicians and nurses receive are incredibly spontaneous, necessitating the ability to work rapidly under constraints on information, time, and resources. The beds are filled from the day to the night, so the Emergency team works like a well-oiled machine to effectively respond to the widest range of cases that could possibly enter Ronald Reagan. This department is an especially valuable experience for our members because they are not constrained with a task: their only job is to learn as much as they can. And from seeing illnesses to traumas to acute crises, the Emergency Medicine Department is the epitome of what a member would want to see on their shift, and the last opportunity they’d want to miss. ",
    },
    {
        department: "Radiation Oncology ",
        description: "The Radiation Oncology department is run through an outpatient clinic in the Medical Plaza of Ronald Reagan Hospital. Throughout the day, Radiation Oncology attendings and residents meet with numerous patients each day, discussing therapeutic options, forming treatment plans with cancer patients, designing molds for radiation devices, and addressing any questions or concerns that are brought up by the patients or their families. While the service lacks a rounding team due its nature as outpatient, the vast amount of services the department offers serve as incredible learning opportunities for PULSE members.",
    },
];

export { departments, Blurb_1 }