const Big_Image = "./assets/members/pulse funny group 23.jpg"

const Pulse_Members = [
    {
        image: "./assets/members/Adanna Chimara.jpg",
        name: "Adanna Chimara (she/her)",
        major: "Psychobiology",
        year: "2025",
        fact: "I met Bill Clinton in 7th grade!",
    },
     {
        image: "./assets/members/Alexandra Tabacu.jpeg",
        name: "Alexandra Tabacu (she/her)",
        major: "Human Biology and Society",
        year: "2026",
        fact: "I didn’t know narwhals existed until I turned 18…",
    },
    {
        image: "./assets/members/Ali Al-Saleem.JPG",
        name: "Ali Al-Saleem (he/him)",
        major: "Human Biology and Society",
        year: "2024",
        fact: "I can cut our eta by 10 min no matter where we’re going",
    },
    {
        image: "./assets/members/Ashley Huh.jpg",
        name: "Ashley huh (she/her))",
        major: "Microbiology, Immunology, and Molecular Genetics ",
        year: "2025",
        fact: "When I was 6, I had beef with the tooth fairy",
    },
    {
        image: "./assets/members/Ashley Presnell.jpg",
        name: "Ashley Presnell (she/her))",
        major: "Microbiology, Immunology, and Molecular Genetics ",
        year: "2025",
        fact: "My morning routine is playing wordle",
    },
    {
        image: "./assets/members/August Blum.jpg",
        name: "August Blum (he/him)",
        major: "Psychobiology ",
        year: "2024",
        fact: "I have visual snow, which basically means my entire visual field has a mild and colorful TV static filter.",
    },
    {
        image: "./assets/members/Austin M.jpg",
        name: "Austin McBride (he/him)",
        major: "Physiological Sciences ",
        year: "2024",
        fact: "I have 60 Spotify playlists all named after colors.",
    },
    {
        image: "./assets/members/Bless Nadeak.jpg",
        name: "Blesscamal Nadeak (he/him)",
        major: "Biology",
        year: "2024",
        fact: "As a kid, I injured my nose and when I sleep it's uncomfortable to nose breath so I mouth breath but not by choice. ",
    },
    {
        image: "./assets/members/Chidera Anthony-Wise.jpg",
        name: "Chidera Anthony-Wise (she/her)",
        major: "Human Biology and Society",
        year: "2024",
        fact: "I performed at California Adventure with my show choir in middle school! ",
    },
    {
        image: "./assets/members/Chloe Remigio.jpg",
        name: "Chloe Remigio (she/her)",
        major: "Human Biology and Society",
        year: "2026",
        fact: "I've never eaten a peanut butter and jelly sandwich.",
    },
    {
        image: "./assets/members/Elizabeth Iniguez-Figueroa.jpg",
        name: "Elizabeth Iniguez (she/her)",
        major: "Physiogical Sciences",
        year: "2024",
        fact: "I love being in nature, and will drive hours to Joshua tree just to look at the stars.",
    },
    {
        image: "./assets/members/Erick Nedd.jpg",
        name: "Erick Nedd (he/him)",
        major: "Microbiology, Immunology, and Molecular Genetics",
        year: "2025",
        fact: "I love learning new languages! I currently speak English, Spanish, French Patois and a little bit of Chinese.",
    },
      {
        image: "./assets/members/Fernanda Madrazo.jpg",
        name: "Fernanda Madrazo (she/her)",
        major: "Human Biology and Society",
        year: "2025",
        fact: "I have a fake tooth.",
    },
      {
        image: "./assets/members/George Kokotsis.jpg",
        name: "George Kokotsis (he/him)",
        major: "Undeclared- Life Sciences",
        year: "2026",
        fact: "I live a days worth of flying away from UCLA",
    },
    {
        image: "./assets/members/Grace.jpg",
        name: "Grace Hajjar (she/her)",
        major: "Physiological Sciences",
        year: "2024",
        fact: "I can remember the food I ordered at a restaurant over a year ago. ",
    },
    {
        image: "./assets/members/Harshi Pandian.jpg",
        name: "Harshitha Pandian (she/her)",
        major: "Molecular, Cell, and Developmental Biology",
        year: "2025",
        fact: "Every vacation I have been on, I have always found a way to injure myself!",
    },
    {
        image: "./assets/members/Helen Benitez .jpg",
        name: "Helen Benitez (she/her)",
        major: "Physiological Sciences",
        year: "2026",
        fact: "I've been Boxing and doing Muay Thai for +10 years.",
    },
    {
        image: "./assets/members/Jacob Dao.jpg",
        name: "Jacob Dao (he/him)",
        major: "Psychobiology",
        year: "2024",
        fact: "I've gotten my toe stuck in an escalator.",
    },
    {
        image: "./assets/members/Janitzy Felix.jpg",
        name: "Janitzy Felix (she/her)",
        major: "Physiological Sciences",
        year: "2024",
        fact: "I am missing a small organ, guess which one (hint: it stores bile) ",
    },
     {
        image: "./assets/members/Jasmine_Nguyen.JPG",
        name: "Jasmine Nguyen (she/her)",
        major: "Environmental Sciences",
        year: "2025",
        fact: "I take the cheese off my pizzas and reassemble the toppings on top. ",
    },
     {
        image: "./assets/members/Jayasree Peri.jpg",
        name: "Jayasree Peri (she/her)",
        major: "Microbiology, Immunology, and Molecular Biology",
        year: "2023",
        fact: "I will point out almost every dog I see to you ",
    },     
    {
        image: "./assets/members/Jonathan Phan.jpg",
        name: "Jonathan Phan (he/him)",
        major: "Bioengineering and Physiological Sciences",
        year: "2024",
        fact: "I once slept for a whole day (26hrs to be exact) after finals week. I legit skipped a day of life. ",
    },
     {
        image: "./assets/members/Joseph Lee.jpg",
        name: "Joseph Lee (he/him)",
        major: "Human Biology and Society",
        year: "2025",
        fact: "I do the NYT mini-crossword every single day ",
    },
    {
        image: "./assets/members/Katherine Fu.jpg",
        name: "Katherine Fu (she/her)",
        major: "Psychobiology",
        year: "2025",
        fact: "I flew from tokyo to sf on my birthday so I experienced my birthday twice (in both time zones). ",
    },
    {
        image: "./assets/members/Kimberly Cabrera.jpg",
        name: "Kimberly Cabrera (she/her)",
        major: "Biology",
        year: "2025",
        fact: "I have a pet bunny! ",
    },
    {
        image: "./assets/members/Madison Chan.JPG",
        name: "Madison Chan (she/her)",
        major: "Public Health",
        year: "2025",
        fact: "I love cooking and experimenting with new recipes!",
    },
    {
        image: "./assets/members/Maeve Settle.jpg",
        name: "Maeve Settle (she/her)",
        major: "Physiological Sciences",
        year: "2025",
        fact: "I know the lyrics to every single Taylor Swift song.",
    },
    {
        image: "./assets/members/Margaret Pham.jpg",
        name: "Margaret Pham (she/her)",
        major: "Biochemistry",
        year: "2024",
        fact: "I'm a Canadian dual citizen!",
    },
    {
        image: "./assets/members/Marlen Hernandez.jpg",
        name: "Marlen Hernandez (she/her)",
        major: "Physiological Sciences",
        year: "2024",
        fact: "I've never broken/fractured a bone *knock on wood*",
    },
     {
        image: "./assets/members/Mathangi Swaminathan.jpg",
        name: "Mathangi Swaminathan (she/her)",
        major: "Psychobiology",
        year: "2026",
        fact: "I love collecting earrings from different places around the world- over a 100 pairs and still counting!",
    },
    {
        image: "./assets/members/Michelle Yeung.jpg",
        name: "Michelle Yeung (she/her)",
        major: "Physiological Sciences",
        year: "2026",
        fact: "I have watched over 75 k-dramas.",
    },
    {
        image: "./assets/members/Monay Martinez.jpg",
        name: "Monay Martinez (she/her)",
        major: "Physiological Sciences",
        year: "2024",
        fact: "II have 12 biological siblings!",
    },
      {
        image: "./assets/members/natalie k.jpg",
        name: "Natalie Keung (she/her)",
        major: "Biology",
        year: "2024",
        fact: "I love being outdoors but I'm allergic to practically everything outside. ",
    },
    {
        image: "./assets/members/NatalieNguyen.jpg",
        name: "Natalie Nguyen (she/her)",
        major: "Psychobiology",
        year: "2026",
        fact: "I can move my left ear, and I’m currently working on moving the right one.",
    },
    {
        image: "./assets/members/Nithya Narapa Reddy.jpg",
        name: "Nithya Narapa Reddy (she/her)",
        major: "Human Biology and Society",
        year: "2025",
        fact: "I can crack my wrists",
    },
     {
        image: "./assets/members/Sai Ramadas.jpg",
        name: "Sai Ramadas (he/him)",
        major: "Molecular, Cell, and Developmental Biology",
        year: "2024",
        fact: "I only found out this summer that a pickle is just a cucumber.",
    },
    {
        image: "./assets/members/Sanam Patel.jpg",
        name: "Sanam Patel (she/her)",
        major: "Human Biology and Society",
        year: "2025",
        fact: "Justin Baldoni dmed me",
    },
    {
        image: "./assets/members/Serena Gill.jpg",
        name: "Serena Gill (she/her)",
        major: "Molecular, Cell, and Developmental Biology",
        year: "2025",
        fact: "I’ve never lost a game of Connect 4. ",
    },
      {
        image: "./assets/members/Simer Shera.jpg",
        name: "Simer Shera (she/her)",
        major: "Microbiology, Immunology, and Molecular Genetics",
        year: "2023",
        fact: "I have two english bulldogs who used to be social media famous ",
    },
    {
        image: "./assets/members/Stuti Pradhan.jpg",
        name: "Stuti Pradhan (she/her)",
        major: "Human Biology and Society",
        year: "2024",
        fact: "I was in a music video with my dance team!",
    },
        {
        image: "./assets/members/Thomas Tran.jpg",
        name: "Thomas Tran (he/him)",
        major: "Microbiology, Immunology, and Molecular Genetics",
        year: "2026",
        fact: "I was a D1 athlete for three months",
    },   
]

export { Pulse_Members, Big_Image }
