name: Deploy Website

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Packages
      run: npm install

    - name: Create new Branch
      run: git checkout -b temp

    - name: Setup Github
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Build Project
      run: npm run build
    
    - name: Delete Files
      run: ls -A | grep -E -v '^(.git|dist)$' | xargs rm -r

    - name: Move Dist Contents out and Delete
      run: |
        cd dist
        mv * ./..
        cd ..
        rm -r dist
    
    - name: Commit Changes on Temp Branch
      run: |
        git add .
        git commit -m "Update Website"
        git fetch origin
        git push --set-upstream origin temp
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout gh-pages Branch
      run: |
        git checkout -b gh-pages origin/gh-pages
        git pull

    - name: Merge and Push Branch
      run: |
        git merge --allow-unrelated-histories temp -m "Updates"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cleanup Remote Branch
      run: |
        git push origin --delete temp
